// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eval_3.Data;

#nullable disable

namespace eval_3.Migrations
{
    [DbContext(typeof(DbEvaluacion))]
    [Migration("20230609191238_EvaluacionMigration")]
    partial class EvaluacionMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eval_3.Models.Book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "Ea non nesciunt distinctio aspernatur eum id id.",
                            name = "Yvette Corwin V"
                        },
                        new
                        {
                            id = 2,
                            description = "Iure quibusdam aut quo qui pariatur eum libero.",
                            name = "Felipa Lindgren DVM"
                        },
                        new
                        {
                            id = 3,
                            description = "At velit et hic modi sunt iure consequatur.",
                            name = "Ollie Rowe"
                        });
                });

            modelBuilder.Entity("eval_3.Models.BookReservation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("book_id")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date_reserve")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("book_id");

                    b.HasIndex("user_id");

                    b.ToTable("Book_reservations");

                    b.HasData(
                        new
                        {
                            id = 1,
                            book_id = 1,
                            code = "cgLFZuT6Y8q7cf0byW",
                            date_reserve = new DateTime(2023, 6, 9, 19, 37, 54, 0, DateTimeKind.Local),
                            user_id = 1
                        },
                        new
                        {
                            id = 2,
                            book_id = 2,
                            code = "6xvGgDMVCYy28epj83P9BUOd",
                            date_reserve = new DateTime(2023, 5, 8, 19, 37, 54, 0, DateTimeKind.Local),
                            user_id = 1
                        },
                        new
                        {
                            id = 3,
                            book_id = 3,
                            code = "If0VJg6Py60FS2Er318",
                            date_reserve = new DateTime(2023, 6, 8, 19, 37, 54, 0, DateTimeKind.Local),
                            user_id = 3
                        });
                });

            modelBuilder.Entity("eval_3.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("cant_reserves_last_month")
                        .HasColumnType("int");

                    b.Property<DateTime?>("date_last_reserve")
                        .HasColumnType("datetime2");

                    b.Property<string>("faculty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            faculty = "Voluptatibus quia voluptatem quia nisi.",
                            name = "Prof. Aleen Konopelski"
                        },
                        new
                        {
                            id = 2,
                            faculty = "Animi laboriosam voluptatum assumenda odit.",
                            name = "Antoinette Mayer"
                        },
                        new
                        {
                            id = 3,
                            faculty = "Et sed quos enim ut quis hic.",
                            name = "Yvonne Terry"
                        });
                });

            modelBuilder.Entity("eval_3.Models.BookReservation", b =>
                {
                    b.HasOne("eval_3.Models.Book", "book")
                        .WithMany("users")
                        .HasForeignKey("book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eval_3.Models.User", "user")
                        .WithMany("reserves")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("book");

                    b.Navigation("user");
                });

            modelBuilder.Entity("eval_3.Models.Book", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("eval_3.Models.User", b =>
                {
                    b.Navigation("reserves");
                });
#pragma warning restore 612, 618
        }
    }
}
